import type { CSSProperties } from "react";

/** Mode-aware surface fills (light: white; dark: navy glass). */
export const SURFACE = {
  bg: "var(--aether-surface, #ffffff)",
  raised: "var(--aether-surface-raised, #f6f6f6)",
  sunken: "var(--aether-surface-sunken, #fafafa)",
  border: "var(--aether-border, #e5e5e5)",
} as const;

/** Semantic Aether text tokens (Phase 37C.2). Prefer these over opacity dimming. */
export const AETHER_TEXT = {
  primary: "var(--aether-text-primary, var(--aether-text, #1a2233))",
  secondary: "var(--aether-text-secondary, #3d4d66)",
  muted: "var(--aether-text-muted, #5a6b85)",
  disabled: "var(--aether-text-disabled, #8a97ad)",
  onAccent: "var(--aether-text-on-accent, #04101f)",
  /** @deprecated Alias for primary — controls now follow theme mode. */
  onLightSurface: "var(--aether-text-primary, var(--aether-text, #1a2233))",
} as const;

export const fullViewportCenter: CSSProperties = {
  minHeight: "100vh",
  display: "grid",
  placeItems: "center",
  fontFamily: "system-ui, -apple-system, Segoe UI, Roboto",
  color: AETHER_TEXT.primary,
};

export const styles: Record<string, CSSProperties> = {
  shell: {
    padding: "1.5rem",
    maxWidth: 1600,
    margin: "0 auto",
    fontFamily: "system-ui, -apple-system, Segoe UI, Roboto",
    color: AETHER_TEXT.primary,
  },
  header: { display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", alignItems: "center", marginBottom: 10 },
  title: { fontSize: 28, fontWeight: 800, color: AETHER_TEXT.primary },
  sub: { color: AETHER_TEXT.secondary },
  actions: { display: "flex", gap: 8, flexWrap: "wrap" },
  nav: { display: "flex", gap: 8, margin: "14px 0" },
  /** Mobile shell: clip horizontal overflow from the scrollable nav strip. */
  shellMobile: {
    overflowX: "hidden",
    maxWidth: "100%",
    boxSizing: "border-box",
    padding: "1rem",
    minWidth: 0,
  },
  /** Touch-friendly horizontal nav; items scroll instead of widening the page. */
  navMobile: {
    display: "flex",
    gap: 8,
    margin: "14px 0",
    overflowX: "auto",
    overflowY: "hidden",
    WebkitOverflowScrolling: "touch",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    minWidth: 0,
    width: "100%",
  },
  navBtnMobile: {
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  mainMobile: {
    display: "grid",
    gap: 14,
    minWidth: 0,
    width: "100%",
  },
  navBtn: {
    padding: "8px 12px",
    borderRadius: 10,
    border: "1px solid var(--aether-border, #ddd)",
    background: "var(--aether-surface, white)",
    color: AETHER_TEXT.primary,
    cursor: "pointer",
  },
  navBtnActive: {
    border: "1px solid var(--aether-accent, #999)",
    background: "var(--aether-accent-soft, transparent)",
    color: AETHER_TEXT.primary,
    fontWeight: 700,
  },
  main: { display: "grid", gap: 14 },
  card: {
    background: "var(--aether-surface-raised, #f6f6f6)",
    padding: 16,
    borderRadius: 14,
    color: AETHER_TEXT.primary,
  },
  cardTitle: { fontSize: 18, fontWeight: 800, marginBottom: 10, color: AETHER_TEXT.primary },
  // Semantic text hierarchy (Phase 37C.2) — spread into inline styles instead of opacity.
  textPrimary: { color: AETHER_TEXT.primary },
  textSecondary: { color: AETHER_TEXT.secondary },
  textMuted: { color: AETHER_TEXT.muted },
  textDisabled: { color: AETHER_TEXT.disabled },
  textOnAccent: { color: AETHER_TEXT.onAccent },
  metaText: { fontSize: 13, color: AETHER_TEXT.muted, lineHeight: 1.45 },
  captionText: { fontSize: 12, color: AETHER_TEXT.muted, lineHeight: 1.35 },
  sectionLead: { margin: "0 0 12px 0", color: AETHER_TEXT.muted },
  ghostBtn: {
    fontSize: 12,
    padding: "4px 10px",
    border: "1px solid var(--aether-border, #ccc)",
    borderRadius: 6,
    background: "transparent",
    color: AETHER_TEXT.primary,
    cursor: "pointer",
  },
  /** Default themed button for unstyled native `<button>` replacements (Phase 37C.2). */
  actionBtn: {
    padding: "6px 12px",
    borderRadius: 8,
    border: `1px solid ${SURFACE.border}`,
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
    cursor: "pointer",
    fontSize: 14,
  },
  // Semantic danger surface: fixed light red bg + dark red text stays readable in
  // both light and dark mode (documented exception — not accent/mode tinted).
  errorBox: { background: "#ffe6e6", color: "#8a1c1c", padding: 12, borderRadius: 12, marginBottom: 10 },
  errorInline: { marginTop: 10, background: "#ffe6e6", color: "#8a1c1c", padding: 10, borderRadius: 12 },
  input: { padding: "8px 10px", borderRadius: 10, border: `1px solid ${SURFACE.border}`, minWidth: 280, background: SURFACE.bg, color: AETHER_TEXT.primary },
  select: { padding: "6px 8px", borderRadius: 10, border: `1px solid ${SURFACE.border}`, background: SURFACE.bg, color: AETHER_TEXT.primary },
  label: { display: "grid", gap: 6, color: AETHER_TEXT.primary },
  listRow: { background: "var(--aether-surface, white)", padding: 12, borderRadius: 12, border: "1px solid var(--aether-panel-border, #e5e5e5)", color: AETHER_TEXT.primary },
  dayRow: { display: "flex", gap: 10, alignItems: "center", background: "var(--aether-surface, white)", padding: 10, borderRadius: 12, border: "1px solid var(--aether-panel-border, #e5e5e5)", color: AETHER_TEXT.primary },
  blockChip: { display: "flex", gap: 6, alignItems: "center", padding: "6px 8px", borderRadius: 12, border: "1px solid var(--aether-panel-border, #ddd)", background: "var(--aether-surface-sunken, #fafafa)", color: AETHER_TEXT.primary },
  timeInput: { width: 76, padding: "4px 6px", borderRadius: 8, border: `1px solid ${SURFACE.border}`, background: SURFACE.bg, color: AETHER_TEXT.primary },
  minInput: { width: 54, padding: "4px 6px", borderRadius: 8, border: `1px solid ${SURFACE.border}`, textAlign: "right", background: SURFACE.bg, color: AETHER_TEXT.primary },
  smallBtn: {
    padding: "2px 6px",
    borderRadius: 8,
    border: `1px solid ${SURFACE.border}`,
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
    cursor: "pointer",
  },
  statusPill: {
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid var(--aether-panel-border, #ddd)",
    background: "var(--aether-surface, white)",
    color: AETHER_TEXT.primary,
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  // Mode-aware semantic status chips (Phase 37C.2): tints flip with theme mode.
  statusOnTrack: {
    border: "1px solid var(--aether-chip-success-border, #b9e6c7)",
    background: "var(--aether-chip-success-bg, #ecfff1)",
    color: "var(--aether-chip-success-text, #1b5e20)",
  },
  statusOverdue: {
    border: "1px solid var(--aether-chip-danger-border, #f2b8b8)",
    background: "var(--aether-chip-danger-bg, #ffecec)",
    color: "var(--aether-chip-danger-text, #8a1c1c)",
  },
  statusIdle: {
    border: "1px solid var(--aether-border, #ddd)",
    background: "var(--aether-surface-sunken, #f8f8f8)",
    color: AETHER_TEXT.secondary,
  },
  statusWarning: {
    border: "1px solid var(--aether-chip-warning-border, #f0d9a8)",
    background: "var(--aether-chip-warning-bg, #fff8e8)",
    color: "var(--aether-chip-warning-text, #7a5b12)",
  },
  /** Mode-aware briefing/review section tints (Phase 37C.2). */
  briefingToneSuccess: {
    borderColor: "var(--aether-chip-success-border, #b9e6c7)",
    background: "var(--aether-chip-success-bg, #ecfff1)",
    color: "var(--aether-chip-success-text, #1b5e20)",
  },
  briefingToneWarm: {
    borderColor: "var(--aether-chip-warning-border, #f0d9a8)",
    background: "var(--aether-chip-warning-bg, #fff8e8)",
    color: "var(--aether-chip-warning-text, #7a5b12)",
  },
  dashboardSection: {
    background: "var(--aether-surface, white)",
    border: "1px solid var(--aether-panel-border, #e5e5e5)",
    padding: 12,
    borderRadius: 12,
    color: AETHER_TEXT.primary,
  },
  dashboardGrid: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
  },
  /** Single-column stat stack for dashboard side rails on desktop. */
  dashboardRailStatGrid: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: "1fr",
  },
  // ---------- Dashboard layout (Phase 32) ----------
  dashboardLayout: {
    display: "grid",
    gap: 12,
    alignItems: "start",
    gridTemplateColumns: "minmax(240px, 320px) minmax(480px, 1fr) minmax(240px, 340px)",
  },
  dashboardLeftRail: {
    minWidth: 0,
    display: "grid",
    gap: 12,
    alignContent: "start",
  },
  dashboardCenter: {
    minWidth: 0,
    display: "grid",
    gap: 12,
    alignContent: "start",
  },
  dashboardRightRail: {
    minWidth: 0,
    display: "grid",
    gap: 12,
    alignContent: "start",
  },
  dashboardStack: {
    display: "grid",
    gap: 12,
  },
  dashboardDetails: {
    display: "grid",
    gap: 12,
    marginTop: 12,
  },
  dashboardCalendarCard: {
    background: "var(--aether-surface, white)",
    border: "1px solid var(--aether-panel-border, #e5e5e5)",
    borderRadius: 12,
    padding: 12,
    display: "grid",
    gap: 10,
  },
  dashboardCalendarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  dashboardQuickActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  dashboardQuickActionBtn: {
    padding: "6px 10px",
    borderRadius: 10,
    border: `1px solid ${SURFACE.border}`,
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
    cursor: "pointer",
    fontSize: 13,
  },
  statCard: {
    background: "var(--aether-surface-sunken, #fafafa)",
    border: "1px solid var(--aether-panel-border, #e5e5e5)",
    borderRadius: 12,
    padding: "12px 14px",
    display: "grid",
    gap: 4,
    color: AETHER_TEXT.primary,
  },
  statValue: {
    fontSize: 22,
    fontWeight: 800,
    lineHeight: 1.2,
    color: AETHER_TEXT.primary,
  },
  statLabel: {
    fontSize: 13,
    color: AETHER_TEXT.secondary,
  },
  progressTrack: {
    width: "100%",
    height: 10,
    borderRadius: 999,
    background: "var(--aether-surface-sunken, #ececec)",
    border: "1px solid var(--aether-border, #e0e0e0)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    background: "var(--aether-accent, #6fcf97)",
    minWidth: 0,
    transition: "width 0.2s ease",
  },
  progressFillXp: {
    height: "100%",
    borderRadius: 999,
    background: "var(--aether-progress-gradient, #7eb8da)",
    minWidth: 0,
    transition: "width 0.2s ease",
  },
  levelBadge: {
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid var(--aether-panel-border, #c5d9e8)",
    background: "var(--aether-accent-soft, #eef6fc)",
    color: AETHER_TEXT.primary,
    fontSize: 12,
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  streakPill: {
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid var(--aether-chip-warning-border, #f0d9a8)",
    background: "var(--aether-chip-warning-bg, #fff8e8)",
    color: "var(--aether-chip-warning-text, #7a5b12)",
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  streakPillMuted: {
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid var(--aether-border, #ddd)",
    background: "var(--aether-surface-sunken, #f8f8f8)",
    color: AETHER_TEXT.muted,
    fontSize: 12,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  timelineRow: {
    background: "var(--aether-surface, white)",
    border: "1px solid var(--aether-panel-border, #e5e5e5)",
    padding: 10,
    borderRadius: 12,
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
    borderLeftWidth: 4,
    borderLeftStyle: "solid",
    color: AETHER_TEXT.primary,
  },
  timelineAccentDone: {
    borderLeftColor: "#6fcf97",
  },
  timelineAccentBehind: {
    borderLeftColor: "#e57373",
  },
  timelineAccentInProgress: {
    borderLeftColor: "#81c784",
  },
  timelineAccentUpcoming: {
    borderLeftColor: "#bdbdbd",
  },
  timelineAccentEvent: {
    borderLeftColor: "#64b5f6",
  },
  timelineAccentMarker: {
    borderLeftColor: "#b39ddb",
  },
  timelineAccentAllDay: {
    borderLeftColor: "#cfd8dc",
  },
  timelineAccentConflict: {
    borderLeftColor: "#e65100",
  },
  // Mode-aware item-type chips (Phase 37C.2).
  statusEvent: {
    border: "1px solid var(--aether-chip-info-border, #90caf9)",
    background: "var(--aether-chip-info-bg, #e3f2fd)",
    color: "var(--aether-chip-info-text, #0d47a1)",
  },
  statusMarker: {
    border: "1px solid var(--aether-chip-marker-border, #ce93d8)",
    background: "var(--aether-chip-marker-bg, #f3e5f5)",
    color: "var(--aether-chip-marker-text, #6a1b9a)",
  },
  statusAllDay: {
    border: "1px solid var(--aether-chip-neutral-border, #cfd8dc)",
    background: "var(--aether-chip-neutral-bg, #eceff1)",
    color: "var(--aether-chip-neutral-text, #37474f)",
  },
  categoryPill: {
    padding: "2px 8px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 800,
    whiteSpace: "nowrap",
    textTransform: "uppercase" as const,
    letterSpacing: "0.02em",
  },
  helpText: {
    fontSize: 12,
    color: AETHER_TEXT.muted,
    lineHeight: 1.35,
  },

  // ---------- Calendar ----------
  calendarLayout: {
    display: "flex",
    gap: 14,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  calendarLayoutMobile: {
    display: "grid",
    gap: 14,
    width: "100%",
    minWidth: 0,
  },
  calendarMain: {
    flex: "1 1 520px",
    minWidth: 0,
    display: "grid",
    gap: 10,
  },
  calendarMainMobile: {
    display: "grid",
    gap: 10,
    minWidth: 0,
    width: "100%",
  },
  calendarSidebar: {
    flex: "0 0 180px",
    background: SURFACE.bg,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: 12,
    padding: 12,
    display: "grid",
    gap: 8,
    alignContent: "start",
    color: AETHER_TEXT.primary,
  },
  calendarCategoryBar: {
    background: SURFACE.bg,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: 12,
    padding: "10px 12px",
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
    color: AETHER_TEXT.primary,
  },
  calendarCategoryToggleRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
    flex: "1 1 auto",
    minWidth: 0,
  },
  calendarToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  calendarToolbarGroup: {
    display: "flex",
    gap: 6,
    alignItems: "center",
    flexWrap: "wrap",
  },
  calendarTitle: {
    fontSize: 18,
    fontWeight: 800,
    margin: 0,
    color: AETHER_TEXT.primary,
  },
  calendarToggle: {
    display: "inline-flex",
    border: `1px solid ${SURFACE.border}`,
    borderRadius: 10,
    overflow: "hidden",
  },
  calendarToggleBtn: {
    padding: "6px 12px",
    border: "none",
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
    cursor: "pointer",
    fontSize: 13,
  },
  calendarToggleBtnActive: {
    background: "var(--aether-accent-soft, #eef6fc)",
    color: AETHER_TEXT.primary,
    fontWeight: 700,
  },
  calendarWeekdayHeader: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 4,
    fontSize: 12,
    fontWeight: 700,
    color: AETHER_TEXT.primary,
    textAlign: "center",
  },
  calendarMonthGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gridAutoRows: "minmax(96px, 1fr)",
    gap: 4,
  },
  calendarDayCell: {
    border: `1px solid ${SURFACE.border}`,
    borderRadius: 8,
    background: SURFACE.bg,
    padding: 4,
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minHeight: 96,
    overflow: "hidden",
    color: AETHER_TEXT.primary,
  },
  calendarDayCellMuted: {
    background: SURFACE.raised,
    opacity: 0.6,
  },
  calendarDayCellToday: {
    border: "1px solid var(--aether-accent, #7eb8da)",
    background: "var(--aether-accent-soft, #f3f9fd)",
  },
  calendarDayNumber: {
    fontSize: 12,
    fontWeight: 700,
    alignSelf: "flex-end",
    color: AETHER_TEXT.primary,
  },
  calendarDayNumberToday: {
    background: "#3b82f6",
    color: "#ffffff",
    borderRadius: 999,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  calendarPill: {
    display: "block",
    width: "100%",
    textAlign: "left",
    border: "1px solid transparent",
    borderRadius: 6,
    padding: "2px 6px",
    fontSize: 11,
    lineHeight: 1.3,
    cursor: "pointer",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: AETHER_TEXT.primary,
  },
  calendarMoreBtn: {
    border: "none",
    background: "transparent",
    fontSize: 11,
    fontWeight: 700,
    color: AETHER_TEXT.primary,
    cursor: "pointer",
    textAlign: "left",
    padding: "1px 4px",
  },
  calendarWeekGrid: {
    display: "grid",
    gridTemplateColumns: "56px repeat(7, 1fr)",
    border: `1px solid ${SURFACE.border}`,
    borderRadius: 10,
    overflow: "hidden",
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
  },
  calendarWeekColHeader: {
    padding: "6px 4px",
    textAlign: "center",
    fontSize: 12,
    fontWeight: 700,
    borderBottom: `1px solid ${SURFACE.border}`,
    borderLeft: `1px solid ${SURFACE.border}`,
    color: AETHER_TEXT.primary,
  },
  calendarWeekColHeaderToday: {
    background: "var(--aether-accent-soft, #f3f9fd)",
    color: AETHER_TEXT.primary,
  },
  calendarAllDayRow: {
    display: "grid",
    gridTemplateColumns: "56px repeat(7, 1fr)",
    borderBottom: `1px solid ${SURFACE.border}`,
    background: SURFACE.raised,
    color: AETHER_TEXT.primary,
  },
  calendarAllDayLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: AETHER_TEXT.primary,
    padding: "4px 6px",
    textTransform: "uppercase",
  },
  calendarAllDayCell: {
    borderLeft: "1px solid var(--aether-border, #f2f2f2)",
    padding: 3,
    display: "grid",
    gap: 2,
    minHeight: 24,
  },
  calendarTimeGutterCell: {
    boxSizing: "border-box",
    fontSize: 10,
    color: AETHER_TEXT.primary,
    textAlign: "right",
    paddingRight: 6,
    paddingTop: 2,
    lineHeight: 1,
    height: 48,
    borderTop: `1px solid ${SURFACE.border}`,
  },
  calendarWeekDayColumn: {
    position: "relative",
    borderLeft: "1px solid var(--aether-border, #f2f2f2)",
  },
  calendarWeekDayColumnToday: {
    background: "var(--aether-accent-soft, #f8fbfe)",
  },
  calendarHourLine: {
    boxSizing: "border-box",
    height: 48,
    borderTop: "1px solid var(--aether-border, #f4f4f4)",
  },
  calendarTimedBlock: {
    position: "absolute",
    left: 2,
    right: 2,
    margin: 0,
    borderRadius: 6,
    border: "1px solid transparent",
    padding: "2px 5px",
    fontSize: 11,
    lineHeight: 1.25,
    overflow: "hidden",
    cursor: "pointer",
    boxSizing: "border-box",
    appearance: "none",
    color: AETHER_TEXT.primary,
  },
  calendarNowLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 2,
    background: "#e53935",
    zIndex: 2,
  },
  calendarCategoryToggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    border: `1px solid ${SURFACE.border}`,
    borderRadius: 8,
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
    padding: "6px 8px",
    cursor: "pointer",
    fontSize: 13,
    textAlign: "left",
  },
  calendarCategoryToggleInline: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: 8,
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
    padding: "4px 10px",
    cursor: "pointer",
    fontSize: 13,
    whiteSpace: "nowrap",
  },
  calendarCategoryToggleHidden: {
    color: AETHER_TEXT.primary,
    opacity: 0.45,
  },
  calendarCategorySwatch: {
    width: 12,
    height: 12,
    borderRadius: 4,
    flex: "0 0 auto",
    border: "1px solid rgba(0,0,0,0.15)",
  },
  calendarModalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.35)",
    display: "grid",
    placeItems: "center",
    padding: 16,
    zIndex: 50,
  },
  calendarModalCard: {
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
    borderRadius: 14,
    padding: 18,
    maxWidth: 420,
    width: "100%",
    boxShadow: "0 12px 32px rgba(0,0,0,0.2)",
    display: "grid",
    gap: 10,
  },
  calendarModalRow: {
    display: "grid",
    gridTemplateColumns: "84px 1fr",
    gap: 8,
    fontSize: 13,
    color: AETHER_TEXT.primary,
  },
  calendarModalLabel: {
    color: AETHER_TEXT.primary,
    fontWeight: 600,
    opacity: 0.7,
  },
  calendarSettingsSection: {
    marginTop: 16,
    border: `1px solid ${SURFACE.border}`,
    borderRadius: 12,
    padding: "12px 14px",
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
  },
  calendarSettingsSummary: {
    cursor: "pointer",
    fontWeight: 800,
    fontSize: 14,
    listStyle: "none",
    color: AETHER_TEXT.primary,
  },
  calendarSettingsBody: {
    display: "grid",
    gap: 16,
    marginTop: 14,
  },
  calendarSettingsGroup: {
    display: "grid",
    gap: 10,
  },
  calendarSettingsGroupTitle: {
    fontWeight: 700,
    fontSize: 13,
    margin: 0,
    color: AETHER_TEXT.primary,
  },
  calendarSettingsRow: {
    display: "grid",
    gap: 8,
    padding: "10px 0",
    borderBottom: "1px solid var(--aether-border, #f0f0f0)",
  },
  calendarSettingsRowHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  calendarSettingsRowLabel: {
    fontWeight: 600,
    fontSize: 13,
    color: AETHER_TEXT.primary,
  },
  calendarSettingsAliasInput: {
    width: "100%",
    maxWidth: 280,
    padding: "6px 8px",
    borderRadius: 8,
    border: `1px solid ${SURFACE.border}`,
    background: SURFACE.bg,
    color: AETHER_TEXT.primary,
    fontSize: 13,
  },
  calendarSettingsActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 4,
  },
  calendarColorPreview: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    color: AETHER_TEXT.primary,
  },
  calendarColorPreviewSwatch: {
    width: 28,
    height: 28,
    borderRadius: 6,
    border: "1px solid rgba(0,0,0,0.15)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 700,
  },
  calendarPaletteFieldset: {
    border: "none",
    margin: 0,
    padding: 0,
    display: "grid",
    gap: 8,
  },
  calendarPaletteGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  calendarPaletteSwatch: {
    width: 22,
    height: 22,
    borderRadius: 5,
    border: "2px solid transparent",
    cursor: "pointer",
    padding: 0,
  },
  calendarPaletteSwatchSelected: {
    border: "2px solid var(--aether-accent, #111827)",
    boxShadow: "0 0 0 1px white inset",
  },
  calendarColorUsageText: {
    fontSize: 12,
    color: AETHER_TEXT.primary,
    margin: 0,
    opacity: 0.75,
  },
};
