import type { CSSProperties } from "react";

export const fullViewportCenter: CSSProperties = {
  minHeight: "100vh",
  display: "grid",
  placeItems: "center",
  fontFamily: "system-ui, -apple-system, Segoe UI, Roboto",
  color: "#333",
};

export const styles: Record<string, CSSProperties> = {
  shell: { padding: "1.5rem", maxWidth: 980, margin: "0 auto", fontFamily: "system-ui, -apple-system, Segoe UI, Roboto" },
  header: { display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", alignItems: "center", marginBottom: 10 },
  title: { fontSize: 28, fontWeight: 800 },
  sub: { opacity: 0.8 },
  actions: { display: "flex", gap: 8, flexWrap: "wrap" },
  nav: { display: "flex", gap: 8, margin: "14px 0" },
  navBtn: { padding: "8px 12px", borderRadius: 10, border: "1px solid #ddd", background: "white" },
  navBtnActive: { border: "1px solid #999", fontWeight: 700 },
  main: { display: "grid", gap: 14 },
  card: { background: "#f6f6f6", padding: 16, borderRadius: 14 },
  cardTitle: { fontSize: 18, fontWeight: 800, marginBottom: 10 },
  errorBox: { background: "#ffe6e6", padding: 12, borderRadius: 12, marginBottom: 10 },
  errorInline: { marginTop: 10, background: "#ffe6e6", padding: 10, borderRadius: 12 },
  input: { padding: "8px 10px", borderRadius: 10, border: "1px solid #ddd", minWidth: 280 },
  select: { padding: "6px 8px", borderRadius: 10, border: "1px solid #ddd" },
  label: { display: "grid", gap: 6 },
  listRow: { background: "white", padding: 12, borderRadius: 12, border: "1px solid #e5e5e5" },
  dayRow: { display: "flex", gap: 10, alignItems: "center", background: "white", padding: 10, borderRadius: 12, border: "1px solid #e5e5e5" },
  blockChip: { display: "flex", gap: 6, alignItems: "center", padding: "6px 8px", borderRadius: 12, border: "1px solid #ddd", background: "#fafafa" },
  timeInput: { width: 76, padding: "4px 6px", borderRadius: 8, border: "1px solid #ddd" },
  minInput: { width: 54, padding: "4px 6px", borderRadius: 8, border: "1px solid #ddd", textAlign: "right" },
  smallBtn: { padding: "2px 6px", borderRadius: 8, border: "1px solid #ddd", background: "white" },
  statusPill: {
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid #ddd",
    background: "white",
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  statusOnTrack: {
    border: "1px solid #b9e6c7",
    background: "#ecfff1",
  },
  statusOverdue: {
    border: "1px solid #f2b8b8",
    background: "#ffecec",
  },
  statusIdle: {
    border: "1px solid #ddd",
    background: "#f8f8f8",
  },
  dashboardSection: {
    background: "white",
    border: "1px solid #e5e5e5",
    padding: 12,
    borderRadius: 12,
  },
  dashboardGrid: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
  },
  statCard: {
    background: "#fafafa",
    border: "1px solid #e5e5e5",
    borderRadius: 12,
    padding: "12px 14px",
    display: "grid",
    gap: 4,
  },
  statValue: {
    fontSize: 22,
    fontWeight: 800,
    lineHeight: 1.2,
  },
  statLabel: {
    fontSize: 13,
    opacity: 0.8,
  },
  progressTrack: {
    width: "100%",
    height: 10,
    borderRadius: 999,
    background: "#ececec",
    border: "1px solid #e0e0e0",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    background: "#6fcf97",
    minWidth: 0,
    transition: "width 0.2s ease",
  },
  progressFillXp: {
    height: "100%",
    borderRadius: 999,
    background: "#7eb8da",
    minWidth: 0,
    transition: "width 0.2s ease",
  },
  levelBadge: {
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid #c5d9e8",
    background: "#eef6fc",
    fontSize: 12,
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  streakPill: {
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid #f0d9a8",
    background: "#fff8e8",
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  streakPillMuted: {
    padding: "4px 10px",
    borderRadius: 999,
    border: "1px solid #ddd",
    background: "#f8f8f8",
    fontSize: 12,
    fontWeight: 600,
    whiteSpace: "nowrap",
    opacity: 0.9,
  },
  timelineRow: {
    background: "white",
    border: "1px solid #e5e5e5",
    padding: 10,
    borderRadius: 12,
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
    borderLeftWidth: 4,
    borderLeftStyle: "solid",
  },
  timelineAccentDone: {
    borderLeftColor: "#6fcf97",
  },
  timelineAccentBehind: {
    borderLeftColor: "#e57373",
  },
  timelineAccentInProgress: {
    borderLeftColor: "#81c784",
  },
  timelineAccentUpcoming: {
    borderLeftColor: "#bdbdbd",
  },
  timelineAccentEvent: {
    borderLeftColor: "#64b5f6",
  },
  timelineAccentMarker: {
    borderLeftColor: "#b39ddb",
  },
  timelineAccentAllDay: {
    borderLeftColor: "#cfd8dc",
  },
  timelineAccentConflict: {
    borderLeftColor: "#e65100",
  },
  statusEvent: {
    border: "1px solid #90caf9",
    background: "#e3f2fd",
  },
  statusMarker: {
    border: "1px solid #ce93d8",
    background: "#f3e5f5",
  },
  statusAllDay: {
    border: "1px solid #cfd8dc",
    background: "#eceff1",
  },
  categoryPill: {
    padding: "2px 8px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 800,
    whiteSpace: "nowrap",
    textTransform: "uppercase" as const,
    letterSpacing: "0.02em",
  },
  helpText: {
    fontSize: 12,
    opacity: 0.75,
    lineHeight: 1.35,
  },

  // ---------- Calendar ----------
  calendarLayout: {
    display: "flex",
    gap: 14,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  calendarMain: {
    flex: "1 1 520px",
    minWidth: 0,
    display: "grid",
    gap: 10,
  },
  calendarSidebar: {
    flex: "0 0 180px",
    background: "white",
    border: "1px solid #e5e5e5",
    borderRadius: 12,
    padding: 12,
    display: "grid",
    gap: 8,
    alignContent: "start",
  },
  calendarToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  calendarToolbarGroup: {
    display: "flex",
    gap: 6,
    alignItems: "center",
    flexWrap: "wrap",
  },
  calendarTitle: {
    fontSize: 18,
    fontWeight: 800,
    margin: 0,
  },
  calendarToggle: {
    display: "inline-flex",
    border: "1px solid #ddd",
    borderRadius: 10,
    overflow: "hidden",
  },
  calendarToggleBtn: {
    padding: "6px 12px",
    border: "none",
    background: "white",
    cursor: "pointer",
    fontSize: 13,
  },
  calendarToggleBtnActive: {
    background: "#eef6fc",
    fontWeight: 700,
  },
  calendarWeekdayHeader: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 4,
    fontSize: 12,
    fontWeight: 700,
    opacity: 0.7,
    textAlign: "center",
  },
  calendarMonthGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gridAutoRows: "minmax(96px, 1fr)",
    gap: 4,
  },
  calendarDayCell: {
    border: "1px solid #ececec",
    borderRadius: 8,
    background: "white",
    padding: 4,
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minHeight: 96,
    overflow: "hidden",
  },
  calendarDayCellMuted: {
    background: "#fafafa",
    opacity: 0.6,
  },
  calendarDayCellToday: {
    border: "1px solid #7eb8da",
    background: "#f3f9fd",
  },
  calendarDayNumber: {
    fontSize: 12,
    fontWeight: 700,
    alignSelf: "flex-end",
  },
  calendarDayNumberToday: {
    background: "#3b82f6",
    color: "white",
    borderRadius: 999,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  calendarPill: {
    display: "block",
    width: "100%",
    textAlign: "left",
    border: "1px solid transparent",
    borderRadius: 6,
    padding: "2px 6px",
    fontSize: 11,
    lineHeight: 1.3,
    cursor: "pointer",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  calendarMoreBtn: {
    border: "none",
    background: "transparent",
    fontSize: 11,
    fontWeight: 700,
    opacity: 0.7,
    cursor: "pointer",
    textAlign: "left",
    padding: "1px 4px",
  },
  calendarWeekGrid: {
    display: "grid",
    gridTemplateColumns: "56px repeat(7, 1fr)",
    border: "1px solid #ececec",
    borderRadius: 10,
    overflow: "hidden",
    background: "white",
  },
  calendarWeekColHeader: {
    padding: "6px 4px",
    textAlign: "center",
    fontSize: 12,
    fontWeight: 700,
    borderBottom: "1px solid #ececec",
    borderLeft: "1px solid #f2f2f2",
  },
  calendarWeekColHeaderToday: {
    background: "#f3f9fd",
    color: "#1d4ed8",
  },
  calendarAllDayRow: {
    display: "grid",
    gridTemplateColumns: "56px repeat(7, 1fr)",
    borderBottom: "1px solid #ececec",
    background: "#fafafa",
  },
  calendarAllDayLabel: {
    fontSize: 10,
    fontWeight: 700,
    opacity: 0.6,
    padding: "4px 6px",
    textTransform: "uppercase",
  },
  calendarAllDayCell: {
    borderLeft: "1px solid #f2f2f2",
    padding: 3,
    display: "grid",
    gap: 2,
    minHeight: 24,
  },
  calendarTimeGutterCell: {
    fontSize: 10,
    opacity: 0.6,
    textAlign: "right",
    paddingRight: 6,
    height: 48,
    borderTop: "1px solid #f4f4f4",
    transform: "translateY(-6px)",
  },
  calendarWeekDayColumn: {
    position: "relative",
    borderLeft: "1px solid #f2f2f2",
  },
  calendarWeekDayColumnToday: {
    background: "#f8fbfe",
  },
  calendarHourLine: {
    height: 48,
    borderTop: "1px solid #f4f4f4",
  },
  calendarTimedBlock: {
    position: "absolute",
    left: 2,
    right: 2,
    borderRadius: 6,
    border: "1px solid transparent",
    padding: "2px 5px",
    fontSize: 11,
    lineHeight: 1.25,
    overflow: "hidden",
    cursor: "pointer",
    boxSizing: "border-box",
  },
  calendarNowLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 2,
    background: "#e53935",
    zIndex: 2,
  },
  calendarCategoryToggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    border: "1px solid #eee",
    borderRadius: 8,
    background: "white",
    padding: "6px 8px",
    cursor: "pointer",
    fontSize: 13,
    textAlign: "left",
  },
  calendarCategoryToggleHidden: {
    opacity: 0.45,
  },
  calendarCategorySwatch: {
    width: 12,
    height: 12,
    borderRadius: 4,
    flex: "0 0 auto",
    border: "1px solid rgba(0,0,0,0.15)",
  },
  calendarModalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.35)",
    display: "grid",
    placeItems: "center",
    padding: 16,
    zIndex: 50,
  },
  calendarModalCard: {
    background: "white",
    borderRadius: 14,
    padding: 18,
    maxWidth: 420,
    width: "100%",
    boxShadow: "0 12px 32px rgba(0,0,0,0.2)",
    display: "grid",
    gap: 10,
  },
  calendarModalRow: {
    display: "grid",
    gridTemplateColumns: "84px 1fr",
    gap: 8,
    fontSize: 13,
  },
  calendarModalLabel: {
    opacity: 0.6,
    fontWeight: 600,
  },
  calendarSettingsSection: {
    marginTop: 16,
    border: "1px solid #eee",
    borderRadius: 12,
    padding: "12px 14px",
    background: "white",
  },
  calendarSettingsSummary: {
    cursor: "pointer",
    fontWeight: 800,
    fontSize: 14,
    listStyle: "none",
  },
  calendarSettingsBody: {
    display: "grid",
    gap: 16,
    marginTop: 14,
  },
  calendarSettingsGroup: {
    display: "grid",
    gap: 10,
  },
  calendarSettingsGroupTitle: {
    fontWeight: 700,
    fontSize: 13,
    margin: 0,
  },
  calendarSettingsRow: {
    display: "grid",
    gap: 8,
    padding: "10px 0",
    borderBottom: "1px solid #f0f0f0",
  },
  calendarSettingsRowHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  calendarSettingsRowLabel: {
    fontWeight: 600,
    fontSize: 13,
  },
  calendarSettingsAliasInput: {
    width: "100%",
    maxWidth: 280,
    padding: "6px 8px",
    borderRadius: 8,
    border: "1px solid #ddd",
    fontSize: 13,
  },
  calendarSettingsActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 4,
  },
  calendarColorPreview: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
  },
  calendarColorPreviewSwatch: {
    width: 28,
    height: 28,
    borderRadius: 6,
    border: "1px solid rgba(0,0,0,0.15)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 700,
  },
  calendarPaletteFieldset: {
    border: "none",
    margin: 0,
    padding: 0,
    display: "grid",
    gap: 8,
  },
  calendarPaletteGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  calendarPaletteSwatch: {
    width: 22,
    height: 22,
    borderRadius: 5,
    border: "2px solid transparent",
    cursor: "pointer",
    padding: 0,
  },
  calendarPaletteSwatchSelected: {
    border: "2px solid #111827",
    boxShadow: "0 0 0 1px white inset",
  },
  calendarColorUsageText: {
    fontSize: 12,
    opacity: 0.75,
    margin: 0,
  },
};
